In [9]:
# Creating an empty list
fruits = []

# Appending elements to the list
fruits.append("apple")
fruits.append("banana")
fruits.append("cherry")

print(fruits)  # Output: ['apple', 'banana', 'cherry']


['apple', 'banana', 'cherry']


In [20]:
# Creating a list with duplicates
fruits = ["apple", "banana", "cherry", "apple"]

# Removing the first occurrence of "apple"
fruits.remove("apple")
#fruits.remove("apple")

print(fruits)  # Output: ['banana', 'cherry', 'apple']


['banana', 'cherry', 'apple']


In [11]:
# Creating a list
fruits = ["apple", "banana", "cherry"]

# Popping the last element
print("Total Fruits : ",fruits) 
last_fruit = fruits.pop()
print("Last Fruit : ",last_fruit)  # Output: 'cherry'
print("Fruits after POP(): ",fruits)      # Output: ['apple', 'banana']

# Popping an element at index 0
first_fruit = fruits.pop(0)
print("First Fruit : ",first_fruit)  # Output: 'apple'
print("Fruits after POP(0): ",fruits)       # Output: ['banana']


Total Fruits :  ['apple', 'banana', 'cherry']
Last Fruit :  cherry
Fruits after POP():  ['apple', 'banana']
First Fruit :  apple
Fruits after POP(0):  ['banana']


In [21]:
# Creating a dictionary
student = {"name": "John", "age": 21, "major": "Computer Science"}

# Getting all keys
keys = student.keys()

print(keys)  # Output: dict_keys(['name', 'age', 'major'])


dict_keys(['name', 'age', 'major'])


: 

In [13]:
for key, value in student.items():
    print(f"{key}: {value}")


name: John
age: 21
major: Computer Science


In [14]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", array_1d)
print("2D Array:\n", array_2d)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3])

# Broadcasting to a 2D array
b = np.array([[1], [2], [3]])

# Adding arrays with broadcasting
result = a + b

print("Broadcasted Addition:\n", result)


Broadcasted Addition:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [16]:
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array_2d)

# Accessing an element at row 1, column 2
print("Element at (1, 1):", array_2d[1, 1])  
print("Element at (2, 2):", array_2d[2, 2]) 
print("Element at (0, 1):", array_2d[0, 1]) 
print("Element at (0, 0):", array_2d[0, 0]) 



[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 1): 5
Element at (2, 2): 9
Element at (0, 1): 2
Element at (0, 0): 1
